<?php

namespace Lottery\PlayBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientDetailsRepository extends EntityRepository
{
}
