<?php

namespace Lottery\PlayBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HasWinningNumbersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasWinningNumbersRepository extends EntityRepository
{
}
