<?php

namespace Lottery\PlayBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WinnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinnerRepository extends EntityRepository
{
}
