parameters:
#    lottery_play.example.class: Lottery\PlayBundle\Example

services:
#    lottery_play.example:
#        class: %lottery_play.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
